/* (c) Copyright 2012 Felipe Magno de Almeida
 *
 * Distributed under the Boost Software License, Version 1.0. (See
 * accompanying file LICENSE_1_0.txt or copy at
 * http://www.boost.org/LICENSE_1_0.txt)
 */

module testing { module inner {

interface modules_allprimitives
{
  boolean foo1();
  char foo2();
  double foo3();
  float foo4();
  long foo5();
  octet foo6();
  short foo7();
  string foo8();
};

}; };
