/* (c) Copyright 2012 Felipe Magno de Almeida
 *
 * Distributed under the Boost Software License, Version 1.0. (See
 * accompanying file LICENSE_1_0.txt or copy at
 * http://www.boost.org/LICENSE_1_0.txt)
 */

typedef sequence<boolean> BooleanSeq;
typedef sequence<char> CharSeq;
typedef sequence<double> DoubleSeq;
typedef sequence<float> FloatSeq;
typedef sequence<long> LongSeq;
typedef sequence<octet> OctetSeq;
typedef sequence<short> ShortSeq;
typedef sequence<string> StringSeq;

interface seq_args_allprimitives
{
  void foo1(in boolean b, in BooleanSeq a);
  void foo2(in char b, in CharSeq a);
  void foo3(in double b, in DoubleSeq a);
  void foo4(in float b, in FloatSeq a);
  void foo5(in long b, in LongSeq a);
  void foo6(in octet b, in OctetSeq a);
  void foo7(in short b, in ShortSeq a);
  void foo8(in string b, in StringSeq a);
};
