/* (c) Copyright 2012 Felipe Magno de Almeida
 *
 * Distributed under the Boost Software License, Version 1.0. (See
 * accompanying file LICENSE_1_0.txt or copy at
 * http://www.boost.org/LICENSE_1_0.txt)
 */

interface allprimitives
{
  void foo1(in boolean a);
  void foo2(in char a);
  void foo3(in double a);
  void foo4(in float a);
  void foo5(in long a);
  void foo6(in octet a);
  void foo7(in short a);
  void foo8(in string a);
  // void foo9(in wchar a);
  // void foo10(in wstring a);
  // void foo11(in any a);
};
